
import {
  Book,
  Folder as FolderIcon,
  FileText,
  PlusCircle,
  Edit3,
  Trash2,
  UploadCloud,
  Sparkles,
  Search,
  ChevronDown,
  ChevronRight,
  Brain,
  XCircle,
  Notebook as NotebookIcon,
  Home,
  Settings,
  MoreHorizontal,
  Save,
  Lightbulb, 
  Bell,      
  Tag,       
  Archive,   
  RefreshCw, 
  LayoutGrid, 
  List, 
  Menu, 
  Bot, 
  Palette, // Added Palette
} from 'lucide-react';

export const Icons = {
  Notebook: NotebookIcon,
  Folder: FolderIcon,
  Note: FileText,
  Add: PlusCircle,
  Edit: Edit3,
  Delete: Trash2,
  Import: UploadCloud,
  AI: Sparkles,
  Search: Search,
  ChevronDown: ChevronDown,
  ChevronRight: ChevronRight,
  Settings: Settings,
  More: MoreHorizontal,
  Save: Save,
  Home: Home,
  Clear: XCircle,
  Lightbulb: Lightbulb,
  Bell: Bell,
  Tag: Tag,
  Archive: Archive,
  Trash: Trash2, 
  Refresh: RefreshCw,
  GridView: LayoutGrid,
  ListView: List,
  Menu: Menu,
  Bot: Bot,
  Palette: Palette, // Added Palette
};

export type IconName = keyof typeof Icons;
